DROP TABLE IF EXISTS passengers;
CREATE TABLE IF NOT EXISTS passengers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(32),
  origin INTEGER DEFAULT NULL,
  destination INTEGER DEFAULT NULL,
  train_id INTEGER DEFAULT NULL,
  station_id INTEGER DEFAULT NULL
);
